image: python:3.11-bullseye

stages:
    - build
    - test

before_script:
    - apt install make

build-job:
    stage: build
    script:
        - echo "Installin packages ..."
        - pip install poetry
        - cd ./api
        - make setup

lintest-1:
    stage: test
    script:
        - echo "Starting linter 1"
        - poetry add black
        - cd ./api
        - poetry run black main.py

lintest-2:
    stage: test
    script:
        - echo "Starting linter 2"
        - poetry add pylint
        - cd ./api
        - poetry run pylint main.py --disable C,W