image: python:3.9

stages:
    - build
    - test

build-job:
    stage: build
    script:
        - echo "Installin packages ..."
        - make setup
        - make activate

lintest-1:
  stage: test
  script:
      - echo "Starting linter 1"
      - pip install black
      - black ./api/main.py

lintest-2:
  stage: test
  script:
      - echo "Starting linter 2"
      - pip install pylint
      - pylint ./api/main.py --disable C,W