image: python:3.11-bullseye

stages:
    - build
    - test

before_script:
    - apt install make

build-job:
    stage: build
    script:
        - echo "Installin packages ..."
        - pip install poetry
        - make setup

lintest-1:
    stage: test
    script:
        - echo "Starting linter 1"
        - poetry add black
        - poetry run black ./api/main.py

lintest-2:
    stage: test
    script:
        - echo "Starting linter 2"
        - poetry add pylint
        - poetry run pylint ./api/main.py --disable C,W