image: python:3.11-bullseye

stages:
    - build
    - test

before_script:
    - apt install make
    - pip install poetry
    - cd ./api

build-job:
    stage: build
    script:
        - echo "Installin packages ..."
        - pip wheel --use-pep517 "pycrypto (==2.6.1)"
        - make setup

lintest-1:
    stage: test
    script:
        - echo "Starting linter 1"
        - poetry add black
        - poetry run black main.py

lintest-2:
    stage: test
    script:
        - echo "Starting linter 2"
        - poetry add pylint
        - poetry run pylint main.py --disable C,W