shapeCorrection:
  goodMatchPercent: 0.15
  mask: './service/api/data/mask.jpg'
align:
  xBorder: 50
  yBorder: 5
  formMapPath: './service/api/config/form_map.yml'
  pointCutX: [20, 95]
  pointCutY: [5, 65]
resultToJson:
  pathToSave: './service/api/result.yml'
